USE QLBongDa
GO

--Câu e--
CREATE OR ALTER PROCEDURE SP_SEL_NO_ENCRYPT @TenCLB nvarchar(100),@TenQG nvarchar(60)
AS
	SELECT  CT.MACT,CT.HOTEN,CT.NGAYSINH,CT.DIACHI,CT.VITRI
	FROM CAUTHU AS CT, CAULACBO AS CLB, QUOCGIA AS QG
	WHERE CT.MACLB=CLB.MACLB AND QG.MAQG=CT.MAQG
		AND QG.TENQG=@TenQG AND CLB.TENCLB=@TenCLB


--Câu f--
GO
CREATE OR ALTER PROCEDURE SP_SEL_ENCRYPT @TenCLB nvarchar(100),@TenQG nvarchar(60) WITH ENCRYPTION
AS
	SELECT  CT.MACT,CT.HOTEN,CT.NGAYSINH,CT.DIACHI,CT.VITRI
	FROM CAUTHU AS CT, CAULACBO AS CLB, QUOCGIA AS QG
	WHERE CT.MACLB=CLB.MACLB AND QG.MAQG=CT.MAQG
		AND QG.TENQG=@TenQG AND CLB.TENCLB=@TenCLB


GO


--Câu g--
EXEC SP_SEL_ENCRYPT N'SHB Ðà Nẵng', N'Brazil'
EXEC SP_SEL_NO_ENCRYPT N'SHB Ðà Nẵng', N'Brazil'
GO

EXEC sp_helptext SP_SEL_NO_ENCRYPT
EXEC sp_helptext SP_SEL_ENCRYPT
GO


--Câu h--
EXEC sp_helptext SP_SEL_ENCRYPT
GO


--Câu i--

--câu 1
CREATE OR ALTER VIEW vCau1 AS
SELECT MACT, HOTEN, NGAYSINH, DIACHI, VITRI
FROM CAUTHU AS CT,CAULACBO AS CLB,QUOCGIA AS QG
WHERE CT.MACLB = CLB.MACLB
  AND CT.MAQG = QG.MAQG
  AND QG.TENQG = N'Brazil'
  AND CLB.TENCLB = N'SHB Ðà Nẵng';
GO

--câu 2
CREATE OR ALTER VIEW vCau2 AS
SELECT MATRAN, NGAYTD, CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2
FROM TRANDAU AS TD, SANVD AS SVD, CAULACBO AS CLB1, CAULACBO AS CLB2
WHERE TD.MASAN = SVD.MASAN
    AND TD.MACLB1 = CLB1.MACLB
    AND TD.MACLB2 = CLB2.MACLB
    AND VONG = 3 AND NAM = 2009;
GO

--câu 3
CREATE OR ALTER VIEW vCau3 AS
SELECT HLV.MAHLV, TENHLV, NGAYSINH, DIACHI, VAITRO, TENCLB
FROM HUANLUYENVIEN AS HLV INNER JOIN HLV_CLB ON HLV.MAHLV = HLV_CLB.MAHLV 
	INNER JOIN CAULACBO AS CLB ON HLV_CLB.MACLB = CLB.MACLB
WHERE MAQG = 'VN'
GO

--câu 4
CREATE OR ALTER VIEW vCau4 AS
SELECT CLB.MACLB,CLB.TENCLB,SVD.TENSAN, SVD.DIACHI,
        (SELECT COUNT(*) FROM CAUTHU AS CT2 WHERE CT2.MACLB = CLB.MACLB AND CT2.MAQG <> 'VN') AS SL
FROM CAULACBO AS CLB, SANVD AS SVD
WHERE CLB.MASAN = SVD.MASAN
    AND (SELECT COUNT(*) FROM CAUTHU AS CT2 WHERE CT2.MACLB = CLB.MACLB AND CT2.MAQG <> 'VN') >= 2;
GO


--câu 5
CREATE OR ALTER VIEW vCau5 AS
SELECT TENTINH, COUNT(MACT) as SLCT
FROM TINH AS T INNER JOIN CAULACBO AS CLB ON T.MATINH = CLB.MATINH
	INNER JOIN CAUTHU AS CT ON CLB.MACLB = CT.MACLB
WHERE CT.VITRI = N'Tiền đạo'
GROUP BY T.MATINH,T.TENTINH

GO

--câu 6
CREATE OR ALTER VIEW vCau6 AS
SELECT CLB.TENCLB, T.TENTINH
FROM CAULACBO AS CLB JOIN TINH AS T on CLB.MATINH = T.MATINH 
	JOIN BANGXH AS BXH on BXH.MACLB = CLB.MACLB
WHERE BXH.VONG = 3 AND BXH.NAM = 2009
    AND BXH.HANG <= (SELECT MIN(BXH1.HANG) FROM BANGXH AS BXH1 WHERE BXH1.VONG = 3 AND BXH1.NAM = 2009)
GO


--câu 7
CREATE OR ALTER VIEW vCau7 AS
SELECT TENHLV
FROM HUANLUYENVIEN AS HLV INNER JOIN HLV_CLB ON HLV.MAHLV = HLV_CLB.MAHLV
WHERE DIENTHOAI = NULL

GO

--câu 8
CREATE OR ALTER VIEW vCau8 AS
SELECT HLV.TENHLV
FROM HUANLUYENVIEN AS HLV, QUOCGIA AS QG
WHERE HLV.MAHLV NOT IN (SELECT HLV_CLB.MAHLV FROM HLV_CLB)
    AND QG.MAQG = HLV.MAQG
    AND QG.TENQG = N'Việt Nam'
GO

--câu 9
CREATE OR ALTER VIEW vCau9 AS
SELECT DISTINCT NGAYTD, TENSAN, CLB1.TENCLB TENCLB1, CLB2.TENCLB TENCLB2, KETQUA
FROM TRANDAU AS TD inner join SANVD AS SVD ON TD.MASAN = SVD.MASAN
	INNER JOIN BANGXH AS BXH ON KETQUA = HIEUSO AND (TD.MACLB1 = BXH.MACLB OR TD.MACLB2 = BXH.MACLB)
	INNER JOIN CAULACBO AS CLB1 ON TD.MACLB1 = CLB1.MACLB
	INNER JOIN CAULACBO AS CLB2 ON TD.MACLB2 = CLB2.MACLB
WHERE TD.VONG <> 4 AND BXH.NAM = 2009 AND HANG = 1
GO

--câu 10
CREATE OR ALTER VIEW vCau10 AS
SELECT DISTINCT TD.NGAYTD, SVD.TENSAN, CLB1.TENCLB TENCLB1, CLB2.TENCLB TENCLB2, TD.KETQUA
FROM TRANDAU AS TD JOIN SANVD AS SVD ON TD.MASAN = SVD.MASAN
	JOIN CAULACBO AS CLB1 ON TD.MACLB1 = CLB1.MACLB 
	JOIN CAULACBO AS CLB2 ON TD.MACLB2 = CLB2.MACLB
	JOIN BANGXH AS BXH ON (CLB1.MACLB = BXH.MACLB or CLB2.MACLB = BXH.MACLB )
WHERE TD.VONG = 3 and TD.NAM = 2009 AND BXH.hang = (SELECT MAX(bxh1.HANG)
                                                    FROM BANGXH AS BXH1
                                                    WHERE BXH1.VONG = 3)
GO


--Phân quyền
--BDRead
GRANT SELECT ON vCau1 TO BDRead;
GRANT SELECT ON vCau2 TO BDRead;
GRANT SELECT ON vCau3 TO BDRead;
GRANT SELECT ON vCau4 TO BDRead;
GRANT SELECT ON vCau5 TO BDRead;
GRANT SELECT ON vCau6 TO BDRead;
GRANT SELECT ON vCau7 TO BDRead;
GRANT SELECT ON vCau8 TO BDRead;
GRANT SELECT ON vCau9 TO BDRead;
GRANT SELECT ON vCau10 TO BDRead;
GO
--BDU01
DENY SELECT ON vCau1 TO BDU01;
DENY SELECT ON vCau2 TO BDU01;
DENY SELECT ON vCau3 TO BDU01;
DENY SELECT ON vCau4 TO BDU01;

GRANT SELECT ON vCau5 TO BDU01;
GRANT SELECT ON vCau6 TO BDU01;
GRANT SELECT ON vCau7 TO BDU01;
GRANT SELECT ON vCau8 TO BDU01;
GRANT SELECT on vCau9 TO BDU01;
GRANT SELECT on vCau10 TO BDU01;
GO

--BDU03
GRANT SELECT ON vCau1 TO BDU03;
GRANT SELECT ON vCau2 TO BDU03;
GRANT SELECT ON vCau3 TO BDU03;
GRANT SELECT ON vCau4 TO BDU03;
GO

--BDU04
GRANT SELECT ON vCau1 TO BDU04;
GRANT SELECT ON vCau2 TO BDU04;
GRANT SELECT ON vCau3 TO BDU04;
GRANT SELECT ON vCau4 TO BDU04;
GO


--Câu j--

--câu 1
CREATE OR ALTER PROCEDURE SPCau1
@TenCLB nvarchar(100), @TenQG nvarchar(60)
AS
SELECT MACT, HOTEN, NGAYSINH, DIACHI, VITRI
FROM CAUTHU AS CT,CAULACBO AS CLB,QUOCGIA AS QG
WHERE CT.MACLB = CLB.MACLB
  AND CT.MAQG = QG.MAQG
  AND QG.TENQG = @TenQG
  AND CLB.TENCLB = @TenCLB;
GO
EXEC SPCau1 N'SHB ÐÀ NẴNG','Brazil';
GO

--câu 2
CREATE OR ALTER PROCEDURE SPCau2
@Vong int, @Nam int
AS
SELECT MATRAN, NGAYTD, CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2
FROM TRANDAU AS TD, SANVD AS S, CAULACBO AS CLB1, CAULACBO AS CLB2
WHERE TD.MASAN = S.MASAN
	AND TD.MACLB1 = CLB1.MACLB
    AND TD.MACLB2 = CLB2.MACLB
    AND VONG = @Vong
    AND NAM = @Nam;
GO

EXEC SPCau2 2009,3;
GO

--câu 3
CREATE OR ALTER PROCEDURE SPCau3
@TenQG nvarchar(100)
AS
SELECT HLV.MAHLV, HLV.TENHLV, HLV.NGAYSINH, HLV.DIACHI, HLV_CLB.VAITRO, CLB.TENCLB
FROM HUANLUYENVIEN AS HLV, QUOCGIA AS QG, HLV_CLB, CAULACBO AS CLB
WHERE HLV_CLB.MACLB = CLB.MACLB
	AND HLV.MAHLV = HLV_CLB.MAHLV
    AND HLV.MAQG = QG.MAQG
    AND QG.TENQG = @TenQG;
GO

EXEC SPCau3 N'Việt Nam';
GO


--câu 4
CREATE OR ALTER PROCEDURE SPCau4
@MaQG varchar(5),@SL int
AS
SELECT CLB.MACLB,CLB.TENCLB,SVD.TENSAN, SVD.DIACHI,
        (SELECT COUNT(*) FROM CAUTHU AS CT2 WHERE CT2.MACLB = CLB.MACLB AND CT2.MAQG <> @MaQG) AS SL
FROM CAULACBO AS CLB, SANVD AS SVD
WHERE CLB.MASAN = SVD.MASAN
    AND (SELECT COUNT(*) FROM CAUTHU AS CT2 WHERE CT2.MACLB = CLB.MACLB AND CT2.MAQG <> @MaQG) >= @SL;
GO

EXEC SPCau4 'VN',2;
GO

--câu 5
CREATE OR ALTER PROCEDURE SPCau5
@Vitri nvarchar(20)
AS
SELECT TENTINH, COUNT(MACT) as SLCT
FROM TINH AS T INNER JOIN CAULACBO AS CLB ON T.MATINH = CLB.MATINH
	INNER JOIN CAUTHU AS CT ON CLB.MACLB = CT.MACLB
WHERE CT.VITRI = @Vitri
GROUP BY T.MATINH,T.TENTINH
GO

EXEC SPCau5 N'Tiền Ðạo';
GO

--câu 6
CREATE OR ALTER PROCEDURE SPCau6
@Vong int,@Nam int
AS
SELECT CLB.TENCLB, T.TENTINH
FROM CAULACBO AS CLB JOIN TINH AS T on CLB.MATINH = T.MATINH 
	JOIN BANGXH AS BXH on BXH.MACLB = CLB.MACLB
WHERE BXH.VONG = @Vong AND BXH.NAM = @Nam
    AND BXH.HANG <= (SELECT MIN(BXH1.HANG) FROM BANGXH AS BXH1 WHERE BXH1.VONG = @Vong AND BXH1.NAM = @Nam);
GO

EXEC SPCau6 3,2009;
GO

--câu 7
CREATE OR ALTER PROCEDURE SPCau7
AS
SELECT TENHLV
FROM HUANLUYENVIEN AS HLV INNER JOIN HLV_CLB ON HLV.MAHLV = HLV_CLB.MAHLV
WHERE DIENTHOAI = NULL

EXEC SPCau7;
GO

--câu 8
CREATE OR ALTER PROCEDURE SPCau8
@TenQG varchar(5)
AS
SELECT HLV.TENHLV
FROM HUANLUYENVIEN AS HLV, QUOCGIA AS QG
WHERE HLV.MAHLV NOT IN (SELECT HLV_CLB.MAHLV FROM HLV_CLB)
    AND QG.MAQG = HLV.MAQG
    AND QG.TENQG = @TenQG
GO

EXEC SPCau8 N'Việt Nam';
GO

--câu 9
CREATE OR ALTER PROCEDURE SPCau9
@Vong int,@Nam int
AS
SELECT DISTINCT NGAYTD, TENSAN, CLB1.TENCLB TENCLB1, CLB2.TENCLB TENCLB2, KETQUA
FROM TRANDAU AS TD inner join SANVD AS SVD ON TD.MASAN = SVD.MASAN
	INNER JOIN BANGXH AS BXH ON KETQUA = HIEUSO AND (TD.MACLB1 = BXH.MACLB OR TD.MACLB2 = BXH.MACLB)
	INNER JOIN CAULACBO AS CLB1 ON TD.MACLB1 = CLB1.MACLB
	INNER JOIN CAULACBO AS CLB2 ON TD.MACLB2 = CLB2.MACLB
WHERE TD.VONG <> @Vong AND BXH.NAM = @Nam AND HANG = 1
GO

EXEC SPCau9 3,2009;
GO

--câu 10
CREATE OR ALTER PROCEDURE SPCau10
@Vong int,@Nam int
AS
SELECT CLB.TENCLB, T.TENTINH
FROM TINH AS T, CAULACBO AS CLB, BANGXH AS BXH
WHERE T.MATINH = CLB.MATINH
	AND CLB.MACLB = BXH.MACLB
    AND BXH.VONG = @Vong
    AND BXH.NAM = @Nam
    AND BXH.HANG >= (SELECT MAX(BXH1.HANG) FROM BANGXH AS BXH1 WHERE BXH1.VONG = @Vong AND BXH1.NAM = @Nam)
GO

EXEC SPCau10 3,2009;
GO

--Phân quyền
--BDURead
GRANT EXECUTE TO BDRead;
GO
---BDU01
GRANT EXECUTE ON SPCau5 TO BDU01;
GRANT EXECUTE ON SPCau6 TO BDU01;
GRANT EXECUTE ON SPCau7 TO BDU01;
GRANT EXECUTE ON SPCau8 TO BDU01;
GRANT EXECUTE ON SPCau9 TO BDU01;
GRANT EXECUTE ON SPCau10 TO BDU01;
GO
---BDU03
GRANT EXECUTE ON SPCau1 TO BDU03;
GRANT EXECUTE ON SPCau2 TO BDU03;
GRANT EXECUTE ON SPCau3 TO BDU03;
GRANT EXECUTE ON SPCau4 TO BDU03;
GO
---BDU04
GRANT EXECUTE ON SPCau1 TO BDU04;
GRANT EXECUTE ON SPCau2 TO BDU04;
GRANT EXECUTE ON SPCau3 TO BDU04;
GRANT EXECUTE ON SPCau4 TO BDU04;
GO

