USE QLDT


--Q1
SELECT HOTEN, LUONG
FROM GIAOVIEN 
WHERE PHAI = N'NỮ'

--Q2
SELECT HOTEN,LUONG*1.1 AS LUONG
FROM GIAOVIEN

---Q3
SELECT DISTINCT GIAOVIEN.MAGV
FROM GIAOVIEN, BOMON
WHERE (GIAOVIEN.HOTEN LIKE N'% NGUYỄN' AND GIAOVIEN.LUONG>2000) OR (YEAR(BOMON.NGAYNHANCHUC) > 1995 AND GIAOVIEN.MAGV = BOMON.TRUONGBM)

---Q4
SELECT HOTEN
FROM GIAOVIEN, BOMON
WHERE (GIAOVIEN.MABM = BOMON.MABM AND BOMON.MAKHOA = 'CNTT')  

---Q5
SELECT GIAOVIEN.HOTEN, BOMON.*
FROM GIAOVIEN, BOMON
WHERE BOMON.TRUONGBM = GIAOVIEN.MAGV

---Q6
SELECT GIAOVIEN.HOTEN, BOMON.*
FROM GIAOVIEN, BOMON
WHERE GIAOVIEN.MABM = BOMON.MABM

---Q7
SELECT DETAI.TENDT, GIAOVIEN.*
FROM DETAI, GIAOVIEN
WHERE DETAI.GVCNDT = GIAOVIEN.MAGV

---Q8
SELECT KHOA.TRUONGKHOA, GIAOVIEN.*
FROM KHOA, GIAOVIEN
WHERE KHOA.TRUONGKHOA = GIAOVIEN.MAGV

---Q9
SELECT GIAOVIEN.*
FROM GIAOVIEN, THAMGIA_DT
WHERE GIAOVIEN.MABM = 'VS' AND THAMGIA_DT.MADT = '006' AND THAMGIA_DT.MAGV = GIAOVIEN.MAGV
 
--Q10
SELECT DETAI.MADT, CHUDE.MACD, GIAOVIEN.HOTEN,GIAOVIEN.NGAYSINH, GIAOVIEN.DIACHI
FROM GIAOVIEN, DETAI, CHUDE
WHERE DETAI.CAPQL = N'THÀNH PHỐ' AND DETAI.GVCNDT = GIAOVIEN.MAGV AND DETAI.MACD = CHUDE.MACD


--Q12
SELECT GV1.HOTEN 
FROM GIAOVIEN AS GV1, GIAOVIEN AS GV2
WHERE GV1.GVQLCM = GV2.MAGV AND GV2.HOTEN = N'Nguyễn Thanh Tùng'

--Q13
SELECT GV.HOTEN 
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE BM.TRUONGBM = GV.MAGV AND BM.TENBM = N'Hệ thống thông tin'

--Q14
SELECT GV.HOTEN
FROM GIAOVIEN AS GV, CHUDE AS CD, DETAI AS DT
WHERE DT.GVCNDT = GV.MAGV AND DT.MACD = CD.MACD AND CD.TENCD = N'Quản lý giáo dục'

--Q15
SELECT CV.TENCV
FROM CONGVIEC AS CV, DETAI AS DT
WHERE CV.MADT = DT.MADT AND DT.TENDT = N'HTTT quản lý các trường ĐH' AND (CV.NGAYBD BETWEEN '2008-03-01' AND '2008-03-31')

--Q16
SELECT GV1.HOTEN,GV2.HOTEN
FROM GIAOVIEN AS GV1, GIAOVIEN AS GV2
WHERE GV1.GVQLCM = GV2.MAGV 

--Q17
SELECT CV.*
FROM CONGVIEC AS CV 
WHERE (CV.NGAYBD BETWEEN '2007-01-01' AND '2007-08-01')

--Q18
SELECT DISTINCT GV2.HOTEN
FROM GIAOVIEN AS GV1, GIAOVIEN AS GV2, BOMON AS BM
WHERE GV1.MABM = BM.MABM AND GV1.MABM = GV2.MABM AND GV1.HOTEN = N'Trần Trà Hương' AND GV2.HOTEN != N'Trần Trà Hương'

--Q19
SELECT GV.*
FROM GIAOVIEN AS GV, BOMON AS BM, DETAI AS DT
WHERE GV.MAGV = BM.TRUONGBM AND GV.MAGV = DT.GVCNDT

--Q20
SELECT GV.*
FROM GIAOVIEN AS GV, BOMON AS BM, KHOA AS K
WHERE GV.MAGV = BM.TRUONGBM AND GV.MAGV = K.TRUONGKHOA

--Q21
SELECT GV.HOTEN
FROM GIAOVIEN AS GV, BOMON AS BM, DETAI AS DT
WHERE GV.MAGV = BM.TRUONGBM AND GV.MAGV = DT.GVCNDT

--Q22
SELECT GV.MAGV
FROM GIAOVIEN AS GV, DETAI AS DT, KHOA AS K
WHERE GV.MAGV = DT.GVCNDT AND GV.MAGV = K.TRUONGKHOA

--Q23
SELECT DISTINCT GV.MAGV 
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT
WHERE GV.MABM = 'HTTT' OR (TGDT.MAGV = GV.MAGV AND TGDT.MADT = '001')

--Q24
SELECT DISTINCT GV2.*
FROM GIAOVIEN AS GV1, GIAOVIEN AS GV2, BOMON AS BM
WHERE GV1.MABM = BM.MABM AND GV1.MABM = GV2.MABM AND GV1.MAGV = '002' AND GV2.MAGV != '002'

--Q25
SELECT GV.*
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE GV.MAGV = BM.TRUONGBM

--Q26
SELECT GV.HOTEN, GV.LUONG
FROM GIAOVIEN AS GV