/* Câu 1 */
SELECT HOTEN, LUONG FROM GIAOVIEN WHERE PHAI = N'Nữ'

/* Câu 2 */
SELECT HOTEN, LUONG AS LUONG_TRUOC, LUONG*1.1 AS LUONG_SAU FROM GIAOVIEN

/* Câu 3 */
SELECT MAGV FROM GIAOVIEN, BOMON WHERE (GIAOVIEN.LUONG > 2000 AND GIAOVIEN.HOTEN LIKE N'Nguyễn%') OR (BOMON.TRUONGBM = GIAOVIEN.MAGV AND YEAR(BOMON.NGAYNHANCHUC) > 1995)

/* Câu 4 */
SELECT HOTEN FROM GIAOVIEN, BOMON, KHOA WHERE GIAOVIEN.MABM = BOMON.MABM AND BOMON.MAKHOA = KHOA.MAKHOA AND KHOA.TENKHOA = N'Công nghệ thông tin'

/* Câu 5 */
SELECT * FROM BOMON LEFT JOIN GIAOVIEN ON GIAOVIEN.MAGV = BOMON.TRUONGBM