/***** TOPIC 3: Q6 - Q26 *****/
/* Q6 */
SELECT * FROM GIAOVIEN LEFT JOIN BOMON ON GIAOVIEN.MABM = BOMON.MABM

/* Q7 */
SELECT DETAI.TENDT, GIAOVIEN.* FROM DETAI LEFT JOIN GIAOVIEN ON GIAOVIEN.MAGV = DETAI.GVCNDT

/* Q8 */
SELECT * FROM KHOA, GIAOVIEN WHERE GIAOVIEN.MAGV = KHOA.TRUONGKHOA

/* Q9 */
SELECT DISTINCT GIAOVIEN.* FROM GIAOVIEN, THAMGIADT, BOMON WHERE THAMGIADT.MADT = '006' AND GIAOVIEN.MAGV = THAMGIADT.MAGV AND GIAOVIEN.MABM = BOMON.MABM AND BOMON.TENBM = N'Vi sinh'

/* Q10 */
SELECT DETAI.MADT, CHUDE.*, GIAOVIEN.HOTEN, GIAOVIEN.NGSINH, GIAOVIEN.DIACHI
FROM DETAI, CHUDE, GIAOVIEN
WHERE DETAI.CAPQL = N'Thành phố' AND DETAI.MACD = CHUDE.MACD AND DETAI.GVCNDT = GIAOVIEN.MAGV

/* Q11 */
SELECT * FROM GIAOVIEN A LEFT JOIN GIAOVIEN B ON A.MAGV = B.GVQLCM

/* Q12 */
SELECT A.HOTEN FROM GIAOVIEN A WHERE A.GVQLCM = (SELECT GIAOVIEN.MAGV FROM GIAOVIEN WHERE GIAOVIEN.HOTEN = N'Nguyễn Thanh Tùng') 

/* Q13 */
SELECT GIAOVIEN.HOTEN FROM GIAOVIEN, BOMON WHERE GIAOVIEN.MAGV = BOMON.TRUONGBM AND BOMON.TENBM = N'Hệ thống thông tin'

/* Q14 */
SELECT DISTINCT GIAOVIEN.HOTEN FROM GIAOVIEN, DETAI, THAMGIADT, CHUDE WHERE (DETAI.MADT = THAMGIADT.MADT AND THAMGIADT.MAGV = GIAOVIEN.MAGV) AND (DETAI.MACD = CHUDE.MACD AND CHUDE.TENCD = N'Quản lý giáo dục')

/* Q15 */
SELECT DISTINCT CONGVIEC.TENCV FROM CONGVIEC, DETAI WHERE (CONGVIEC.MADT = DETAI.MADT AND DETAI.TENDT = N'HTTT quản lý các trường ĐH') AND datediff(m, CONGVIEC.NGAYBD, '3/1/2008') = 0

/* Q16 */
SELECT A.HOTEN AS HOTEN_GV, B.HOTEN AS HOTEN_GVGLCM FROM GIAOVIEN A LEFT JOIN GIAOVIEN B ON B.MAGV = A.GVQLCM

/* Q17 */
SELECT * FROM CONGVIEC WHERE DATEDIFF(d, CONGVIEC.NGAYBD, '1/1/2007') < 0 AND DATEDIFF(d, CONGVIEC.NGAYBD, '8/1/2007') > 0

/* Q18 */
SELECT DISTINCT GIAOVIEN.HOTEN FROM GIAOVIEN, BOMON WHERE GIAOVIEN.MABM = (SELECT BOMON.MABM FROM GIAOVIEN, BOMON WHERE BOMON.MABM = GIAOVIEN.MABM AND GIAOVIEN.HOTEN = N'Trần Trà Hương') AND GIAOVIEN.HOTEN != N'Trần Trà Hương'

/* Q19 */
SELECT DISTINCT GIAOVIEN.* FROM GIAOVIEN, DETAI, KHOA WHERE GIAOVIEN.MAGV = KHOA.TRUONGKHOA AND GIAOVIEN.MAGV = DETAI.GVCNDT

/* Q20 */
SELECT GIAOVIEN.HOTEN FROM GIAOVIEN, BOMON, KHOA WHERE GIAOVIEN.MAGV = BOMON.TRUONGBM AND GIAOVIEN.MAGV = KHOA.TRUONGKHOA

/* Q21 */
SELECT DISTINCT GIAOVIEN.HOTEN FROM GIAOVIEN, DETAI, BOMON WHERE GIAOVIEN.MAGV = BOMON.TRUONGBM AND GIAOVIEN.MAGV = DETAI.GVCNDT

/* Q22 */
SELECT DISTINCT GIAOVIEN.MAGV FROM GIAOVIEN, DETAI, KHOA WHERE GIAOVIEN.MAGV = KHOA.TRUONGKHOA AND GIAOVIEN.MAGV = DETAI.GVCNDT

/* Q23 */
SELECT DISTINCT GIAOVIEN.MAGV FROM GIAOVIEN, BOMON, THAMGIADT WHERE (GIAOVIEN.MABM = N'HTTT') OR (GIAOVIEN.MAGV = THAMGIADT.MAGV AND THAMGIADT.MADT = '001')

/* Q24 */
SELECT GIAOVIEN.* FROM GiAOVIEN WHERE GIAOVIEN.MABM = (SELECT GIAOVIEN.MABM FROM GIAOVIEN WHERE GIAOVIEN.MAGV = '002') AND GIAOVIEN.MAGV != '002'

/* Q25 */
SELECT GIAOVIEN.* FROM GIAOVIEN, BOMON WHERE GIAOVIEN.MAGV = BOMON.TRUONGBM

/* Q26 */
SELECT HOTEN, LUONG FROM GIAOVIEN




/***** TOPIC 4: Q27 - Q34 *****/
/* Q27 */
SELECT COUNT(*) AS SLGV, SUM(LUONG) AS TONG_LUONG
FROM GIAOVIEN

/* Q28 */
SELECT MABM, COUNT(*) AS SLGV, AVG(LUONG) AS LUONG_TB
FROM GIAOVIEN
GROUP BY MABM

/* Q29 */
SELECT CHUDE.TENCD, COUNT (DETAI.MADT) AS SL_DT
FROM CHUDE LEFT JOIN DETAI ON CHUDE.MACD = DETAI.MACD
GROUP BY CHUDE.MACD, CHUDE.TENCD

/* Q30 */
SELECT HOTEN, COUNT (DISTINCT THAMGIADT.MADT) AS SL_DT
FROM GIAOVIEN LEFT JOIN THAMGIADT ON GIAOVIEN.MAGV = THAMGIADT.MAGV
GROUP BY GIAOVIEN.MAGV, GIAOVIEN.HOTEN

/* Q31 */
SELECT HOTEN, COUNT (DETAI.GVCNDT) AS SL_DT_CN
FROM GIAOVIEN LEFT JOIN DETAI ON GIAOVIEN.MAGV = DETAI.GVCNDT
GROUP BY GIAOVIEN.MAGV, GIAOVIEN.HOTEN

/* Q32 */
SELECT HOTEN, COUNT (NGUOITHAN.TEN)
FROM GIAOVIEN LEFT JOIN NGUOITHAN ON GIAOVIEN.MAGV = NGUOITHAN.MAGV
GROUP BY GIAOVIEN.MAGV, GIAOVIEN.HOTEN

/* Q33 */
SELECT GIAOVIEN.HOTEN
FROM GIAOVIEN, THAMGIADT
WHERE GIAOVIEN.MAGV = THAMGIADT.MAGV
GROUP BY GIAOVIEN.MAGV, GIAOVIEN.HOTEN
HAVING COUNT (DISTINCT THAMGIADT.MADT) >= 3

/* Q34 */
SELECT COUNT(DISTINCT THAMGIADT.MAGV) AS SL_GV_THAMGIA_UNGDUNGHHXANH
FROM DETAI, THAMGIADT
WHERE DETAI.TENDT = N'Ứng dụng hoá học xanh' AND DETAI.MADT = THAMGIADT.MADT
GROUP BY THAMGIADT.MADT