USE hellmo

--Q27
SELECT COUNT(*) AS 'TONG GIAO VIEN', SUM(LUONG) AS 'TONG LUONG'
FROM GIAOVIEN 
WHERE LUONG IS NOT NULL

--Q28
SELECT COUNT(*) AS 'TONG GIAO VIEN', AVG(LUONG) AS 'LUONG TRUNG BINH'
FROM GIAOVIEN 
WHERE LUONG IS NOT NULL

--Q29
SELECT CD.TENCD, COUNT(DT.MACD) AS 'SO LUONG DE TAI'
FROM CHUDE AS CD LEFT JOIN DETAI AS DT
ON CD.MACD = DT.MACD AND DT.MACD IS NOT NULL
GROUP BY CD.TENCD

--Q30
SELECT GV.HOTEN, COUNT(DISTINCT TGDT.MADT) AS 'SO LUONG DE TAI'
FROM GIAOVIEN AS GV LEFT JOIN THAMGIADT AS TGDT
ON TGDT.MAGV = GV.MAGV AND TGDT.MAGV IS NOT NULL 
GROUP BY GV.HOTEN

--Q31
SELECT GV.HOTEN, COUNT(DISTINCT DT.MADT) AS 'SO LUONG DE TAI CHU NHIEM'
FROM GIAOVIEN AS GV LEFT JOIN DETAI AS DT
ON GV.MAGV = DT.GVCNDT AND DT.GVCNDT IS NOT NULL 
GROUP BY GV.MAGV,GV.HOTEN

--Q32
SELECT GV.HOTEN, COUNT(NT.MAGV) AS 'SO NGUOI THAN'
FROM GIAOVIEN AS GV LEFT JOIN NGUOI_THAN AS NT
ON GV.MAGV = NT.MAGV AND NT.MAGV IS NOT NULL 
GROUP BY GV.HOTEN

--Q33
SELECT GV.HOTEN
FROM GIAOVIEN AS GV LEFT JOIN THAMGIADT AS TGDT
ON GV.MAGV = TGDT.MAGV AND TGDT.MAGV IS NOT NULL 
GROUP BY GV.HOTEN
HAVING COUNT(DISTINCT TGDT.MAGV) >= 3

--Q34
SELECT COUNT(DT.MADT) AS 'SO LUONG GIAO VIEN'
FROM THAMGIADT AS TGDT, DETAI AS DT, GIAOVIEN AS GV
WHERE DT.TENDT = N'Ứng dụng hóa học xanh' AND GV.MAGV = TGDT.MAGV AND TGDT.MADT = DT.MADT