-- CREATTE DATABASE
CREATE DATABASE T10

USE T10


-- CREATE TABLE
CREATE TABLE PHONGMAY
(
	IDToaNha char(5),
	IDPhongMay char(5),
	TenPhong nvarchar(30)
	primary key(IDToaNha, IDPhongMay)
)

CREATE TABLE TOA_NHA
(
	IDToaNha char(5),
	ten nvarchar(30),
	IDServer char(5)
	primary key(IDToaNha)
)

CREATE TABLE MAYTINH
(
	IDToaNha char(5),
	IDMayTinh char(5),
	TenMay nvarchar(30)unique,
	IDPhong char(5)
	primary key(IDToaNha, IDMayTinh)
)


-- ADD FOREIGN KEY
ALTER TABLE TOA_NHA
ADD CONSTRAINT FK_TN_MT
FOREIGN KEY(IDServer)
REFERENCES MAYTINH(IDMayTinh)

ALTER TABLE PHONGMAY
ADD CONSTRAINT FK_PM_TN
FOREIGN KEY(IDToaNha)
REFERENCES TOA_NHA(IDToaNha)

ALTER TABLE MAYTINH
ADD CONSTRAINT FK_MT_TN
FOREIGN KEY(IDToaNha)
REFERENCES TOA_NHA(IDToaNha)

ALTER TABLE MAYTINH
ADD CONSTRAINT FK_MT_PM
FOREIGN KEY(IDPhong)
REFERENCES PHONGMAY(IDPhongMay)


-- INSERT VALUES
-- INSERT TABLE TOA_NHA
INSERT INTO TOA_NHA (IDToaNha,ten)
VALUES ('N01',N'Tòa nhà mới')

INSERT INTO TOA_NHA (IDToaNha,ten)
VALUES ('N02',N'Dãy F')


-- INSERT TABLE PHONGMAY
INSERT INTO PHONGMAY
VALUES ('N01','I51',N'Phòng Server tòa nhà I')

INSERT INTO PHONGMAY
VALUES ('N01','I52',N'Phòng máy 52')

INSERT INTO PHONGMAY
VALUES ('N02','F00',N'Phòng Server dãy F')


-- INSERT TABLE MAYTINH
INSERT INTO MAYTINH
VALUES ('N01','M01','LAB51-WS01','I51')

INSERT INTO MAYTINH
VALUES ('N01','M02','LAB52-WS01','I52')

INSERT INTO MAYTINH
VALUES ('N01','M03','LAB52-WS02','I52')


--UPDATE TABLE TOA_NHA
UPDATE TOA_NHA
SET IDServer = 'M01'
WHERE IDToaNha = 'N01'

UPDATE TOA_NHA
SET IDServer = 'M01'
WHERE IDToaNha = 'N02'