/*----------------------------------------------------------
MASV: 20127318
HO TEN: Phan Trí Tài
LAB: 03
NGAY: 14/04/2023
----------------------------------------------------------*/
--CAU LENH TAO DB
--a)
CREATE DATABASE QLSV;
GO
USE QLSV;
GO

/*----------------------------------------------------------
MASV: 20127318
HO TEN: Phan Trí Tài
LAB: 03
NGAY: 14/04/2023
----------------------------------------------------------*/
--CAC CAU LENH TAO TABLE
--b)
CREATE TABLE SINHVIEN(
    MASV NVARCHAR(20) NOT NULL ,
    HOTEN NVARCHAR(20) NOT NULL ,
    NGAYSINH DATETIME,
    DIACHI NVARCHAR(200),
    MALOP VARCHAR(20),
    TENDN NVARCHAR(100) NOT NULL UNIQUE ,
    MATKHAU VARBINARY(MAX) NOT NULL
    CONSTRAINT PK_SINHVIEN PRIMARY KEY (MASV)
);

CREATE TABLE NHANVIEN(
    MANV NVARCHAR(20) NOT NULL ,
    HOTEN NVARCHAR(20) NOT NULL ,
    EMAIL NVARCHAR(20),
    LUONG VARBINARY(MAX) NOT NULL,
    TENDN NVARCHAR(100) NOT NULL UNIQUE ,
    MATKHAU VARBINARY(MAX) NOT NULL
    CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV)
);

CREATE TABLE LOP(
    MALOP VARCHAR(20) NOT NULL ,
    TENLOP NVARCHAR(100) NOT NULL ,
    MANV NVARCHAR(20) ,
    CONSTRAINT PK_LOP PRIMARY KEY (MALOP)
);


ALTER TABLE LOP ADD CONSTRAINT FK_LOP_NHANVIEN FOREIGN KEY (MANV)
REFERENCES NHANVIEN (MANV)

ALTER TABLE SINHVIEN ADD CONSTRAINT FK_SINHVIEN_LOP FOREIGN KEY (MALOP)
REFERENCES LOP (MALOP)




/*----------------------------------------------------------
MASV: 20127318
HO TEN: Phan Trí Tài
LAB: 03
NGAY: 14/04/2023
----------------------------------------------------------*/
--CAU LENH TAO STORED PROCEDURE
--c)

	--i)THEM DU LIEU SINH VIEN
GO
CREATE OR ALTER PROCEDURE SP_INS_SINHVIEN(
    @MASV NVARCHAR(20),
    @HOTEN NVARCHAR(20),
    @NGAYSINH DATETIME,
    @DIACHI NVARCHAR(200),
    @MALOP VARCHAR(20),
    @TENDN NVARCHAR(100),
    @MATKHAU NVARCHAR(100)
) AS
BEGIN
    INSERT INTO SINHVIEN (MASV, HOTEN, NGAYSINH, DIACHI, MALOP, TENDN, MATKHAU)
    VALUES (@MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, HASHBYTES('MD5', @MATKHAU))
END;


	--ii)THEM DU LIEU NHAN VIEN
GO
CREATE OR ALTER PROCEDURE SP_INS_NHANVIEN(
    @MANV NVARCHAR(20),
    @HOTEN NVARCHAR(20),
    @EMAIL NVARCHAR(20),
    @LUONG INT,
    @TENDN NVARCHAR(100),
    @MATKHAU NVARCHAR(100) 
) AS BEGIN
    IF NOT EXISTS(
        SELECT * FROM sys.symmetric_keys
        WHERE NAME = 'KEY_NHANVIEN'
        )
    BEGIN
		CREATE SYMMETRIC KEY KEY_NHANVIEN
		WITH ALGORITHM = AES_256
        ENCRYPTION BY PASSWORD = '20127318';
    END
    OPEN SYMMETRIC KEY KEY_NHANVIEN
    DECRYPTION BY PASSWORD = '20127318';

    INSERT INTO NHANVIEN (MANV, HOTEN, EMAIL, LUONG, TENDN, MATKHAU)
    VALUES (@MANV, @HOTEN, @EMAIL, CAST(ENCRYPTBYKEY(KEY_GUID('KEY_NHANVIEN'), 
								   CAST(@LUONG AS VARCHAR)) AS VARBINARY(MAX)) , @TENDN, HASHBYTES('SHA1', @MATKHAU));

    CLOSE SYMMETRIC KEY KEY_NHANVIEN
END;

	--iii) TRUY VAN DU LIEU NHAN VIEN
GO
CREATE OR ALTER PROCEDURE SP_SEL_NHANVIEN
AS
BEGIN
	OPEN SYMMETRIC KEY KEY_NHANVIEN
	DECRYPTION BY PASSWORD = '20127318';
	SELECT MANV, HOTEN, EMAIL, CONVERT(VARCHAR(MAX),DECRYPTBYKEY(LUONG)) AS LUONG FROM NHANVIEN
END


/*----------------------------------------------------------
MASV: 20127318
HO TEN: Phan Trí Tài
LAB: 03
NGAY: 14/04/2023
----------------------------------------------------------*/
--d)
-- XAC MINH TAI KHOAN SINH VIEN PROCEDURE
GO
CREATE OR ALTER PROCEDURE SP_AUTHEN_SINHVIEN(
    @TENDN NVARCHAR(100),
    @MATKHAU NVARCHAR(100)
) 
AS 
BEGIN
	SELECT MASV, HOTEN, NGAYSINH, DIACHI, MALOP from SINHVIEN
	WHERE TENDN = @TENDN and MATKHAU = HASHBYTES('MD5', @MATKHAU);
END;

GO
CREATE OR ALTER PROCEDURE SP_AUTHEN_NHANVIEN(
    @TENDN NVARCHAR(100),
    @MATKHAU NVARCHAR(100)
) 
AS 
BEGIN
	SELECT *
	FROM NHANVIEN
	WHERE TENDN = @TENDN and 
		MATKHAU = HASHBYTES('SHA1', @MATKHAU)
END;
GO

--INSERT SINHVIEN
EXEC SP_INS_SINHVIEN 
	'SV01', 'NGUYEN VAN A', '11/1/2001', '280 AN DUONG VUONG', '19CNTN', 'SVA', '123456'

EXEC SP_INS_SINHVIEN 
	'SV02', 'NGUYEN VAN B', '07/12/2002', '280 AN DUONG VUONG', '20CSH1', 'SVB', '123456'

EXEC SP_INS_SINHVIEN 
	'SV03', 'NGUYEN VAN C', '06/07/2001', '280 AN DUONG VUONG', '19CTT4', 'SVC', '123456'


--INSERT NHANVIEN
EXEC SP_INS_NHANVIEN
	'NV01','LE VAN A','NVA@',3000000,'NVA','123456';

EXEC SP_INS_NHANVIEN
	'NV02','LE VAN B','NVA@',3000000,'NVB','123456';

EXEC SP_INS_NHANVIEN
	'NV03','LE VAN C','NVA@',3000000,'NVC','123456';

EXEC SP_INS_NHANVIEN
	'NV04','LE VAN D','NVA@',3000000,'NVD','123456';


--INSERT LOP
INSERT INTO LOP (MALOP, TENLOP, MANV) VALUES ('19CTT4', N'K19 CNTT lớp 4', 'NV01');
INSERT INTO LOP (MALOP, TENLOP, MANV) VALUES ('19CNTN', N'CNTT Cử nhân tài năng','NV02');
INSERT INTO LOP (MALOP, TENLOP, MANV) VALUES ('20CTT3', N'K20 CNTT lớp 3', 'NV03');
INSERT INTO LOP (MALOP, TENLOP, MANV) VALUES ('20CSH1', N'K20 CNSH lớp 1', 'NV04');



--AUTHENTICATION
EXEC SP_AUTHEN_SINHVIEN 'SVA', '123456';

EXEC SP_AUTHEN_NHANVIEN 'NVA','123456';

--SELECT NHANVIEN
EXEC SP_SEL_NHANVIEN