USE hellmo

--Q35
SELECT DISTINCT GV.LUONG
FROM GIAOVIEN AS GV
WHERE GV.LUONG >= ALL(SELECT GV1.LUONG
	FROM GIAOVIEN AS GV1)

--Q36
SELECT GV.*
FROM GIAOVIEN AS GV
WHERE GV.LUONG >= ALL(SELECT GV1.LUONG
	FROM GIAOVIEN AS GV1) 

--Q37
SELECT GV.*
FROM GIAOVIEN AS GV
WHERE GV.LUONG >= ALL(SELECT GV1.LUONG
	FROM GIAOVIEN AS GV1 WHERE GV1.MABM = 'HTTT')
	AND GV.MABM = 'HTTT'

--Q38
SELECT GV.HOTEN
FROM GIAOVIEN AS GV
WHERE GV.NGSINH <= ALL(SELECT GV1.NGSINH
	FROM GIAOVIEN AS GV1)

--Q39
SELECT GV.HOTEN
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE BM.MABM = GV.MABM AND BM.TENBM = N'Hệ thống thông tin' AND GV.NGSINH >= ALL(SELECT GV1.NGSINH
	FROM GIAOVIEN AS GV1, BOMON AS BM1
	WHERE BM1.MABM = GV1.MABM AND BM1.TENBM = N'Hệ thống thông tin') 

--Q40
SELECT GV.HOTEN, K.TENKHOA
FROM GIAOVIEN AS GV, BOMON AS BM, KHOA AS K
WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA AND GV.LUONG >= ALL(SELECT GV1.LUONG
	FROM GIAOVIEN AS GV1)

--Q41
SELECT GV.*
FROM GIAOVIEN AS GV,BOMON AS BM
WHERE GV.MABM = BM.MABM AND GV.LUONG >= ALL(SELECT GV1.LUONG
	FROM GIAOVIEN AS GV1, BOMON AS BM1
	WHERE GV1.MABM = GV.MABM)

--Q42
SELECT DISTINCT DT.TENDT
FROM GIAOVIEN AS GV, DETAI AS DT, THAMGIADT AS TG
WHERE DT.TENDT NOT IN (SELECT DISTINCT DT1.TENDT
	FROM GIAOVIEN AS GV1, DETAI AS DT1, THAMGIADT AS TG1
	WHERE GV1.HOTEN = N'Nguyễn Hoài An' AND GV1.MAGV = TG1.MAGV AND TG1.MADT = DT1.MADT)


--Q43
SELECT DISTINCT DT.TENDT, GV2.HOTEN
FROM GIAOVIEN AS GV, DETAI AS DT, THAMGIADT AS TG, GIAOVIEN AS GV2
WHERE DT.TENDT NOT IN (SELECT DISTINCT DT1.TENDT
	FROM GIAOVIEN AS GV1, DETAI AS DT1, THAMGIADT AS TG1
	WHERE GV1.HOTEN = N'Nguyễn Hoài An' AND GV1.MAGV = TG1.MAGV AND TG1.MADT = DT1.MADT) 
	AND DT.GVCNDT = GV2.MAGV 

--Q44
SELECT GV.HOTEN
FROM GIAOVIEN AS GV,KHOA AS K, BOMON AS BM
WHERE GV.MABM = BM.MABM AND K.MAKHOA = BM.MAKHOA AND K.TENKHOA = N'Công nghệ thông tin'
AND GV.MAGV NOT IN (SELECT TG.MAGV FROM THAMGIADT AS TG) 

--Q45
SELECT GV.*
FROM GIAOVIEN AS GV
WHERE GV.MAGV NOT IN (SELECT TG.MAGV FROM THAMGIADT AS TG)

--Q46
SELECT GV.*
FROM GIAOVIEN AS GV
WHERE GV.LUONG > (SELECT LUONG 
	FROM GIAOVIEN AS GV1
	WHERE GV1.HOTEN = N'Nguyễn Hoài An')

--Q47
SELECT DISTINCT GV.*
FROM GIAOVIEN AS GV, THAMGIADT AS DT,BOMON AS BM
WHERE GV.MAGV = DT.MAGV AND BM.TRUONGBM = GV.MAGV AND DT.MADT IN(SELECT DT1.MADT
	FROM THAMGIADT AS DT1)

--Q48
SELECT GV1.*
 FROM GIAOVIEN AS GV1, GIAOVIEN AS GV2
 WHERE GV1.HOTEN = GV2.HOTEN AND GV2.PHAI = GV1.PHAI  AND GV1.MAGV != GV2.MAGV AND GV1.MABM = GV2.MABM

--Q49
SELECT GV.*
FROM GIAOVIEN AS GV
WHERE GV.LUONG > (SELECT MIN(GV1.LUONG)
	FROM GIAOVIEN AS GV1, BOMON AS BM1
	WHERE GV1.MABM = BM1.MABM AND BM1.TENBM = N'Công nghệ phần mềm')

--Q50
SELECT GV.*
FROM GIAOVIEN AS GV
WHERE GV.LUONG > ALL (SELECT GV1.LUONG
	FROM GIAOVIEN AS GV1, BOMON AS BM
	WHERE GV1.MABM = BM.MABM AND BM.TENBM = N'Hệ thống thông tin')

--Q51
SELECT K.TENKHOA
FROM GIAOVIEN AS GV, KHOA AS K, BOMON AS BM
WHERE K.MAKHOA = BM.MAKHOA AND GV.MABM = BM.MABM
GROUP BY K.TENKHOA
HAVING COUNT(GV.MAGV) >= ALL(SELECT COUNT(GV1.MAGV)
	FROM BOMON AS BM1, GIAOVIEN AS GV1,KHOA AS K1
	WHERE GV1.MABM = BM1.MABM  AND K1.MAKHOA = BM1.MAKHOA
	GROUP BY K1.TENKHOA)
						  
--Q52
SELECT GV.HOTEN
FROM GIAOVIEN AS GV, DETAI AS DT
WHERE GV.MAGV = DT.GVCNDT 
GROUP BY GV.HOTEN
HAVING COUNT(*) >= ALL (SELECT COUNT(GV1.MAGV)
	FROM GIAOVIEN AS GV1, DETAI AS DT1
	WHERE GV1.MAGV = DT1.GVCNDT 
	GROUP BY GV1.MAGV)

--Q53
SELECT BM.MABM
FROM GIAOVIEN AS GV JOIN BOMON AS BM ON GV.MABM=BM.MABM
GROUP BY BM.MABM
HAVING COUNT(BM.MABM) >= ALL(SELECT COUNT(BM1.MABM)
	FROM GIAOVIEN AS GV1 JOIN BOMON AS BM1 ON GV1.MABM = BM1.MABM
	GROUP BY BM1.MABM)

--Q54
SELECT GV.HOTEN, BM.TENBM
FROM GIAOVIEN AS GV JOIN BOMON AS BM ON GV.MABM = BM.MABM JOIN THAMGIADT AS DT ON DT.MAGV = GV.MAGV
GROUP BY GV.HOTEN, BM.TENBM
HAVING COUNT(DT.MADT) >= ALL(SELECT COUNT(DT1.MADT)
	FROM GIAOVIEN AS GV1 JOIN THAMGIADT AS DT1 ON GV1.MAGV = DT1.MAGV
	GROUP BY GV1.MAGV)

--Q55
SELECT GV.HOTEN
FROM GIAOVIEN AS GV, BOMON AS BM, THAMGIADT AS TGDT
WHERE GV.MABM = BM.MABM AND BM.MABM = 'HTTT' AND GV.MAGV = TGDT.MAGV
GROUP BY GV.HOTEN
HAVING COUNT(TGDT.MAGV) >= ALL(SELECT COUNT(TGDT1.MAGV)
	FROM GIAOVIEN AS GV1, THAMGIADT AS TGDT1
	WHERE GV1.MAGV = TGDT1.MAGV
	GROUP BY TGDT1.MAGV)                         
							  
--Q56
SELECT GV.HOTEN,BM.TENBM
FROM GIAOVIEN AS GV,BOMON AS BM,NGUOI_THAN AS NT
WHERE GV.MABM = BM.MABM AND NT.MAGV = GV.MAGV
GROUP BY GV.HOTEN,BM.TENBM
HAVING COUNT(NT.MAGV) >= ALL(SELECT COUNT(NT1.MAGV)
	FROM GIAOVIEN AS GV1, NGUOI_THAN AS NT1
	WHERE GV1.MAGV = NT1.MAGV
	GROUP BY NT1.MAGV)

--Q57
SELECT GV.HOTEN
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE GV.MAGV = BM.TRUONGBM AND GV.MAGV IN(SELECT GVCNDT
	FROM DETAI AS DT
	GROUP BY GVCNDT
	HAVING COUNT(*) >= ALL(SELECT COUNT(*) FROM DETAI GROUP BY GVCNDT))