USE hellmo

-- Q35
SELECT DISTINCT GV.LUONG
FROM GIAOVIEN AS GV
WHERE GV.LUONG >= ALL(SELECT GV1.LUONG
	FROM GIAOVIEN AS GV1)

-- Q36
SELECT GV.*
FROM GIAOVIEN AS GV
WHERE GV.LUONG >= ALL(SELECT GV1.LUONG
	FROM GIAOVIEN AS GV1) 

-- Q37
SELECT GV.*
FROM GIAOVIEN AS GV
WHERE GV.LUONG >= ALL(SELECT GV1.LUONG
	FROM GIAOVIEN AS GV1 WHERE GV1.MABM = 'HTTT')
	AND GV.MABM = 'HTTT'

-- Q38
SELECT GV.HOTEN
FROM GIAOVIEN AS GV
WHERE GV.NGSINH <= ALL(SELECT GV1.NGSINH
	FROM GIAOVIEN AS GV1)

-- Q39
SELECT GV.HOTEN
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE BM.MABM = GV.MABM AND BM.TENBM = N'Hệ thống thông tin' AND GV.NGSINH >= ALL(SELECT GV1.NGSINH
	FROM GIAOVIEN AS GV1, BOMON AS BM1
	WHERE BM1.MABM = GV1.MABM AND BM1.TENBM = N'Hệ thống thông tin') 

-- Q40
SELECT GV.HOTEN, K.TENKHOA
FROM GIAOVIEN AS GV, BOMON AS BM, KHOA AS K
WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA AND GV.LUONG >= ALL(SELECT GV1.LUONG
	FROM GIAOVIEN AS GV1)

-- Q41
SELECT GV.*
FROM GIAOVIEN AS GV,BOMON AS BM
WHERE GV.MABM = BM.MABM AND GV.LUONG >= ALL(SELECT GV1.LUONG
	FROM GIAOVIEN AS GV1, BOMON AS BM1
	WHERE GV1.MABM = GV.MABM)

-- Q42
SELECT DISTINCT DT.TENDT
FROM GIAOVIEN AS GV, DETAI AS DT, THAMGIADT AS TG
WHERE DT.TENDT NOT IN (SELECT DISTINCT DT1.TENDT
	FROM GIAOVIEN AS GV1, DETAI AS DT1, THAMGIADT AS TG1
	WHERE GV1.HOTEN = N'Nguyễn Hoài An' AND GV1.MAGV = TG1.MAGV AND TG1.MADT = DT1.MADT)


-- Q43
SELECT DISTINCT DT.TENDT, GV2.HOTEN
FROM GIAOVIEN AS GV, DETAI AS DT, THAMGIADT AS TG, GIAOVIEN AS GV2
WHERE DT.TENDT NOT IN (SELECT DISTINCT DT1.TENDT
	FROM GIAOVIEN AS GV1, DETAI AS DT1, THAMGIADT AS TG1
	WHERE GV1.HOTEN = N'Nguyễn Hoài An' AND GV1.MAGV = TG1.MAGV AND TG1.MADT = DT1.MADT) 
	AND DT.GVCNDT = GV2.MAGV 

-- Q44
SELECT GV.HOTEN
FROM GIAOVIEN AS GV,KHOA AS K, BOMON AS BM
WHERE GV.MABM = BM.MABM AND K.MAKHOA = BM.MAKHOA AND K.TENKHOA = N'Công nghệ thông tin'
AND GV.MAGV NOT IN (SELECT TG.MAGV FROM THAMGIADT AS TG) 

-- Q45
SELECT GV.*
FROM GIAOVIEN AS GV
WHERE GV.MAGV NOT IN (SELECT TG.MAGV FROM THAMGIADT AS TG)