USE hellmo

--Q58

--Q59
SELECT TENDT
FROM DETAI AS DT
WHERE DT.MADT IN(SELECT DT.MADT
    FROM DETAI AS DT
    WHERE NOT EXISTS (SELECT GV.MAGV
          FROM GIAOVIEN AS GV
          WHERE GV.MABM = 'HTTT'
          EXCEPT
          SELECT TG.MAGV
          FROM THAMGIADT AS TG
          WHERE DT.MADT = TG.MADT)
          )

--Q60

--Q61
SELECT *
FROM GIAOVIEN AS GV
WHERE NOT EXISTS (SELECT DT.MADT
      FROM DETAI AS DT
      WHERE DT.MACD = 'QLGD'
      EXCEPT 
      SELECT TG.MADT
      FROM THAMGIADT AS TG
      WHERE GV.MAGV = TG.MAGV)
        
--Q62

--Q63
SELECT TENDT
FROM DETAI AS DT
WHERE DT.MADT IN(SELECT DT.MADT
    FROM DETAI AS DT
    WHERE NOT EXISTS (SELECT GV.MAGV
          FROM GIAOVIEN AS GV, BOMON AS BM
          WHERE GV.MABM = BM.MABM AND BM.TENBM = N'Hóa hữu cơ'
          EXCEPT
          SELECT TG.MAGV
          FROM THAMGIADT AS TG
          WHERE DT.MADT = TG.MADT)
         )
       
--Q64

--Q65
SELECT *
FROM GIAOVIEN AS GV
WHERE NOT EXISTS (SELECT DT.MADT
      FROM DETAI AS DT, CHUDE AS CD
      WHERE DT.MACD = CD.MACD AND CD.TENCD = N'Ứng dụng công nghệ'
      EXCEPT 
      SELECT TG.MADT
      FROM THAMGIADT AS TG
      WHERE GV.MAGV = TG.MAGV)
