USE hellmo

--Q66
SELECT GV.HOTEN
FROM GIAOVIEN AS GV, DETAI AS DT, THAMGIADT TG
WHERE TG.MADT = DT.MADT AND GV.MAGV = TG.MAGV 
GROUP BY GV.HOTEN, GV.MAGV
HAVING COUNT(DISTINCT DT.MADT) = (SELECT COUNT(*)
								FROM  GIAOVIEN AS GV1, DETAI AS DT1
								WHERE GV1.MAGV = DT1.GVCNDT AND GV1.HOTEN = N'Trần Trà Hương')

--Q67
SELECT DT.TENDT
FROM DETAI AS DT
WHERE DT.MADT IN(SELECT DT.MADT
    FROM DETAI AS DT
    WHERE NOT EXISTS (SELECT GV.MAGV
          FROM GIAOVIEN AS GV, BOMON AS BM
          WHERE GV.MABM = BM.MABM AND BM.MAKHOA = 'CNTT'
          EXCEPT
          SELECT TG.MAGV
          FROM THAMGIADT AS TG
          WHERE DT.MADT = TG.MADT)
         )

--Q68
SELECT GV.HOTEN
FROM GIAOVIEN AS GV
WHERE NOT EXISTS (SELECT * 
				FROM  CONGVIEC AS CV, DETAI AS DT
				WHERE CV.MADT = DT.MADT AND DT.TENDT = N'Nghiên cứu tế bào gốc' AND
				NOT EXISTS (SELECT *
							FROM THAMGIADT t
							WHERE DT.MADT = t.MADT AND CV.SOTT = t.STT AND t.MAGV = GV.MAGV)
				)

--Q69
SELECT GV.HOTEN
FROM GIAOVIEN AS GV, DETAI AS DT, THAMGIADT AS TG
WHERE DT.KINHPHI > 100000000 AND DT.MADT = TG.MADT AND TG.MAGV = GV.MAGV  
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT DT.MADT) = (SELECT COUNT(*)
								FROM DETAI AS DT1
								WHERE DT1.KINHPHI > 100000000)

--Q70
SELECT DT.TENDT
FROM DETAI AS DT
WHERE NOT EXISTS (SELECT GV.MAGV
				FROM  GIAOVIEN AS GV, KHOA AS K, BOMON AS BM
				WHERE K.TENKHOA = N'Sinh học' AND K.MAKHOA = BM.MAKHOA AND BM.MABM = GV.MABM 
				EXCEPT
				SELECT GV1.MAGV
				FROM GIAOVIEN AS GV1, THAMGIADT AS TG
				WHERE TG.MAGV = GV1.MAGV AND DT.MADT = TG.MADT  
				)

--Q71
SELECT GV.MAGV, GV.HOTEN, GV.NGSINH
FROM GIAOVIEN AS GV, THAMGIADT AS TG
WHERE GV.MAGV = TG.MAGV AND TG.MADT IN (SELECT DT.MADT 
										FROM DETAI AS DT
										WHERE DT.TENDT = N'Ứng dụng hóa học xanh')
GROUP BY GV.MAGV, GV.HOTEN, GV.NGSINH
HAVING COUNT(DISTINCT TG.STT) = (SELECT COUNT(CV.SOTT)
								FROM CONGVIEC AS CV, DETAI AS DT
								WHERE CV.MADT = DT.MADT AND DT.TENDT = N'Ứng dụng hóa học xanh') 

--Q72
SELECT GV.MAGV, GV.HOTEN, BM.TENBM, GV1.HOTEN 
FROM GIAOVIEN AS GV, BOMON AS BM, GIAOVIEN AS GV1
WHERE GV.MABM = BM.MABM AND GV.GVQLCM = GV1.MAGV 
			AND NOT EXISTS (SELECT DT.MADT
							FROM  DETAI AS DT, CHUDE AS CD
							WHERE DT.MACD = CD.MACD AND CD.TENCD = N'Nghiên cứu phát triển'
			AND NOT EXISTS ( SELECT TG.MADT
							FROM THAMGIADT AS TG
							WHERE TG.MAGV = GV.MAGV  AND DT.MADT = TG.MADT)
							)	