-- A
SELECT GV1.MAGV ,GV1.HOTEN, GV2.MAGV, GV2.HOTEN
FROM GIAOVIEN AS GV1 LEFT JOIN GIAOVIEN AS GV2 ON GV1.MAGV = GV2.GVQLCM

--B
SELECT BM.MABM, BM.TENBM, GV.MAGV, GV.HOTEN, (SELECT COUNT(*) 
		FROM GIAOVIEN WHERE GIAOVIEN.MABM = BM.MABM)
		FROM GIAOVIEN AS GV RIGHT JOIN BOMON AS BM ON GV.MAGV = BM.TRUONGBM

--C
SELECT GV.MAGV, GV.HOTEN ,GV.PHAI ,CV.TENCV
FROM GIAOVIEN AS GV LEFT JOIN THAMGIADT AS TG ON GV.MAGV = TG.MAGV LEFT JOIN CONGVIEC CV ON TG.MADT = CV.MADT AND TG.STT = CV.SOTT 
WHERE GV.PHAI = N'Nam'

--D
SELECT GV.MAGV , GV.HOTEN , TG.MADT , CV.SOTT , CV.TENCV
FROM GIAOVIEN AS GV LEFT JOIN THAMGIADT AS TG ON GV.MAGV = TG.MAGV  LEFT JOIN CONGVIEC AS CV ON TG.MADT = CV.MADT AND TG.STT = CV.SOTT AND TG.MADT = '001'

--E
SELECT GV.MAGV , GV.HOTEN , GV.NGSINH
FROM GIAOVIEN AS GV JOIN BOMON AS BM ON GV.MAGV = BM.TRUONGBM
WHERE 2014 - YEAR(GV.NGSINH) >= (CASE PHAI
									WHEN N'Nam' THEN 60
									WHEN N'Nữ'  THEN 55 
									END)
--F
SELECT K.TRUONGKHOA, K.TENKHOA, (CASE PHAI 
									WHEN N'Nam' THEN 60 + YEAR(GV.NGSINH) 
									WHEN N'Nữ'  THEN 55 + YEAR(GV.NGSINH) 
									END) as NAMVEHUU
FROM GIAOVIEN AS GV JOIN KHOA AS K ON GV.MAGV = K.TRUONGKHOA

--G
CREATE TABLE DANHSACHTHIDUA (
	MAGV CHAR(3),
	SODTDAT INT,
	DANHHIEU NVARCHAR(30),
	CONSTRAINT PK_DANHSACHTHIDUA 
	PRIMARY KEY(MAGV)
)


ALTER TABLE DANHSACHTHIDUA
ADD CONSTRAINT FK_DANHSACHTHIDUA_GIAOVIEN
FOREIGN KEY(MAGV)
REFERENCES GIAOVIEN(MAGV)


INSERT INTO DANHSACHTHIDUA(MAGV, SODTDAT)
SELECT GV.MAGV, count(TGDT.MADT) AS sldtdat
FROM GIAOVIEN AS GV left join THAMGIADT AS TGDT on GV.MAGV = TGDT.MAGV and TGDT.KETQUA = N'Đạt'
GROUP BY GV.MAGV


UPDATE DANHSACHTHIDUA
SET DANHHIEU =(CASE 
				WHEN SODTDAT = 0 THEN N'chưa hoàn thành nhiệm vụ'
				WHEN SODTDAT >= 1 and SODTDAT <= 2 THEN N'hoàn thành nhiệm vụ'
				WHEN SODTDAT >= 3 and SODTDAT <= 5 THEN N'tiên tiến'
				WHEN SODTDAT >= 6 THEN N'lao động xuất sắc'
				END)