USE QLDT

--Câu 1
SELECT GV.HOTEN 
FROM GIAOVIEN AS GV, DETAI AS DT, THAMGIADT AS TGDT, CHUDE AS CD 
WHERE (DT.MADT = TGDT.MADT AND TGDT.MAGV = GV.MAGV) AND (DT.MACD = CD.MACD AND CD.TENCD = N'Quản lý giáo dục')


--Câu 2
SELECT GV.HOTEN FROM GIAOVIEN AS GV JOIN BOMON AS BM ON GV.MAGV = BM.TRUONGBM 
WHERE BM.MAKHOA NOT IN (                         
SELECT K.MAKHOA                         
FROM KHOA AS K                          
WHERE K.TENKHOA = N'Công nghệ thông tin') AND GV.MAGV IN (
	SELECT TGDT.MAGV                     
	FROM THAMGIADT AS TGDT JOIN CONGVIEC AS CV  ON TGDT.MADT = CV.MADT AND TGDT.STT = CV.SOTT            
	JOIN DETAI AS DT ON CV.MADT = DT.MADT                     
	JOIN CHUDE AS CD ON DT.MACD  = CD.MACD                     
	WHERE CD.TENCD = N'Thành Phố Thông Minh') 


--Câu 3
SELECT GV.HOTEN 
FROM GIAOVIEN AS GV JOIN BOMON AS BM ON GV.TENBM = N'Hệ thống thông tin' 
GROUP BY GV.HOTEN, GV.LUONG  
HAVING NOT EXISTS (     
	SELECT *     
	FROM GIAOVIEN AS GV1 JOIN BOMON AS BM1 ON GV1.TENBM = N'Hệ thống thông tin'     
	WHERE GV1.LUONG > GV.LUONG) 


--Câu 4
SELECT GV.HOTEN, DATEDIFF(YEAR, GV.NGSINH, GETDATE()) 
FROM GIAOVIEN AS GV JOIN BOMON AS BM ON GV.MAGV = BM.TRUONGBM 
GROUP BY GV.HOTEN, GV.NGSINH 
HAVING NOT EXISTS (     
	SELECT *     
	FROM GIAOVIEN AS GV1 JOIN BOMON AS BM1 ON GV1.MAGV = BM1.TRUONGBM     
	WHERE DATEDIFF(YEAR, GV1.NGSINH, GETDATE()) > DATEDIFF(YEAR, GV.NGSINH, GETDATE()))


--Câu 5
SELECT * 
FROM GIAOVIEN AS GV JOIN BOMON AS BM ON GV.MABM = BM.MABM   
SELECT GV.MAGV, GV.HOTEN, COUNT (DISTINCT TGDT.MADT) AS SOLUONG 
FROM GIAOVIEN AS GV JOIN BOMON AS BM ON GV.MABM = BM.MABM 
				JOIN KHOA AS K ON BM.MAKHOA = K.MAKHOA 
				JOIN THAMGIADT AS TGDT ON TGDT.MAGV = GV.MAGV 
				JOIN CONGVIEC AS CV  ON TGDT.MADT = CV.MADT AND  TGDT.STT = CV.SOTT 
				JOIN DETAI AS DT ON CV.MADT = DT.MADT 
				JOIN CHUDE AS CD ON DT.MACD = CD.MACD 
WHERE BM.MAKHOA = 'CNTT' AND CD.TENCD = N'Quản lý giáo dục' GROUP BY GV.MAGV, GV.HOTEN


--Câu 6
SELECT GV.MAGV, GV.HOTEN 
FROM GIAOVIEN AS GV JOIN BOMON AS BM ON GV.MABM = BM.MABM 
				JOIN KHOA AS K ON BM.MAKHOA = K.MAKHOA 
				JOIN THAMGIADT AS TGDT ON TGDT.MAGV = GV.MAGV 
				JOIN CONGVIEC AS CV  ON TGDT.MADT = CV.MADT AND  TGDT.STT = CV.SOTT 
				JOIN DETAI AS DT ON CV.MADT = DT.MADT 
				JOIN CHUDE AS CD ON DT.MACD = CD.MACD 
WHERE BM.MAKHOA = 'CNTT' AND CD.TENCD = N'Quản lý giáo dục' 
GROUP BY GV.MAGV, GV.HOTEN 
HAVING COUNT(DISTINCT DT.MADT) >= ALL(
	SELECT COUNT( DISTINCT DT.MADT)                        
	FROM GIAOVIEN AS GV JOIN BOMON AS BM ON GV.MABM = BM.MABM                         
					JOIN KHOA AS K ON BM.MAKHOA = K.MAKHOA                         
					JOIN THAMGIADT AS TGDT ON TGDT.MAGV = GV.MAGV                         
					JOIN CONGVIEC AS CV  ON TGDT.MADT = CV.MADT AND  TGDT.STT = CV.SOTT                         
					JOIN DETAI AS DT ON CV.MADT = DT.MADT                         
					JOIN CHUDE AS CD ON DT.MACD = CD.MACD                         
	WHERE BM.MAKHOA = 'CNTT' AND CD.TENCD = N'Quản lý giáo dục')


--Câu 7
SELECT DISTINCT GV.MAGV 
FROM GIAOVIEN AS GV JOIN BOMON AS BM  ON  GV.MABM = BM.MABM 
WHERE  DATEDIFF(YEAR, GV.NGSINH , GETDATE()) >= ALL ( 
	SELECT MAX(DATEDIFF(YEAR, GV.NGSINH , GETDATE()))                             
	FROM GIAOVIEN AS GV JOIN BOMON AS BM ON GV.MABM = BM.MABM                         
					JOIN KHOA AS K ON BM.MAKHOA = K.MAKHOA                         
					JOIN THAMGIADT AS TGDT ON TGDT.MAGV = GV.MAGV                         
					JOIN CONGVIEC AS CV  ON TGDT.MADT = CV.MADT AND  TGDT.STT = CV.SOTT                         
					JOIN DETAI AS DT ON CV.MADT = DT.MADT                         
					JOIN CHUDE AS CD ON DT.MACD = CD.MACD                                                         
	GROUP BY BM.MABM)


--Câu 8
SELECT GV.HOTEN  
FROM GIAOVIEN AS GV JOIN BOMON AS BM ON BM.TRUONGBM = GV.MAGV 
WHERE GV.MAGV NOT IN  (             
	SELECT TGDT.MAGV  
    FROM THAMGIADT AS TGDT, DETAI AS DT             
	WHERE TGDT.MADT= DT.MADT AND YEAR(DT.NGAYBD) = 2011)



--Câu 9
SELECT DISTINCT GV.MAGV AS MA_GV_TG 
FROM GIAOVIEN AS GV, BOMON AS BM, KHOA AS K, THAMGIADT AS TGDT, DETAI AS DT 
WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA AND GV.MAGV = TGDT.MAGV AND TGDT.MADT = DT.MADT AND BM.TRUONGBM = DT.GVCNDT AND GV.MAGV <> DT.GVCNDT


--Câu 10
SELECT DISTINCT AVG(YEAR(GETDATE()) - YEAR(GV.NGSINH)) TUOITB 
FROM GIAOVIEN AS GV, THAMGIADT AS TGDT, DETAI AS DT, CHUDE AS CD 
WHERE GV.MAGV = TGDT.MAGV AND TG.MADT = DT.MADT AND CD.MACD = DT.MACD AND CD.TENCD = N'Quản lý giáo dục' AND GV.MABM != (   
	SELECT GV.MABM 
	FROM GIAOVIEN AS GV   
	WHERE GV.HOTEN= N'Trần Trà Hương')


--Câu 11
SELECT GV.MAGV, GV.HOTEN 
FROM GIAOVIEN AS GV JOIN BOMON AS BM ON GV.MABM = BM.MABM 
				JOIN KHOA AS K ON BM.MAKHOA = K.MAKHOA 
				JOIN THAMGIADT AS TGDT ON TG.MAGV = GV.MAGV 
				JOIN CONGVIEC AS CV  ON TGDT.MADT = CV.MADT AND  TGDT.STT = CV.SOTT 
				JOIN DETAI AS DT ON CV.MADT = DT.MADT JOIN CHUDE AS CD ON DT.MACD = CD.MACD 
WHERE BM.MAKHOA = 'CNTT' AND CD.TENCD = N'Quản lý giáo dục' 
GROUP BY GV.MAGV, GV.HOTEN 
HAVING COUNT(DISTINCT(TGDT.MADT)) =  (
	SELECT COUNT(*)             
	FROM CHUDE AS CD JOIN DETAI AS DT ON CD.MACD = DT.MACD             
	WHERE CD.TENCD = N'Quản lý giáo dục')


--Câu 12
SELECT AVG(DATEDIFF(YEAR, GV.NGSINH, GETDATE())) AS TUOI 
FROM  GIAOVIEN AS GV  
WHERE GV.MAGV NOT IN (
	SELECT TGDT.MAGV                 
	FROM THAMGIADT AS TGDT JOIN CONGVIEC AS CV  ON TGDT.MADT = CV.MADT AND  TGDT.STT = CV.SOTT 
					JOIN DETAI AS DT ON CV.MADT = DT.MADT                 
					JOIN CHUDE AS CD ON DT.MACD = CD.MACD                 
	WHERE CD.TENCD = N'Quản lý giáo dục') AND GV.GVQLCM NOT IN (     
		SELECT GV1.MAGV     
		FROM GIAOVIEN AS GV1     
		WHERE GV1.HOTEN = N'Nguyễn Văn An')


--Câu 13
--Câu 14
SELECT DISTINCT GIAOVIEN.HOTEN 
FROM GIAOVIEN AS GV, BOMON AS BM
WHERE GV.MABM = (
	SELECT BM.MABM 
	FROM GIAOVIEN AS GV1, BOMON AS BM1 
	WHERE BM1.MABM = GV1.MABM AND GV1.HOTEN = N'Trần Trà Hương') AND GV1.HOTEN != N'Trần Trà Hương')


--Câu 15

