USE hellmo

--Q75
SELECT GV.HOTEN, BM.TENBM
FROM BOMON AS BM RIGHT JOIN GIAOVIEN AS GV ON BM.TRUONGBM = GV.MAGV

--Q76
SELECT BM.TENBM, GV.HOTEN
FROM BOMON AS BM LEFT JOIN GIAOVIEN AS GV ON BM.TRUONGBM = GV.MAGV

--Q77
SELECT GV.HOTEN, DT.*
FROM DETAI AS DT RIGHT JOIN GIAOVIEN AS GV ON DT.GVCNDT = GV.MAGV

--Q78

--Q79
SELECT MAGV, HOTEN, (CASE
					WHEN LUONG < 1800 THEN N'THẤP'
					WHEN LUONG >= 1800 AND LUONG <= 2200 THEN N'TRUNG BÌNH'
					WHEN LUONG > 2200 THEN N'CAO'
					END) AS MUCLUONG
FROM GIAOVIEN

--Q80
SELECT GV1.MAGV, GV1.HOTEN, (SELECT COUNT(*)
							FROM GIAOVIEN AS GV2
							WHERE GV2.LUONG >= GV1.LUONG AND GV2.MAGV != GV1.MAGV
							)AS HANG 
FROM GIAOVIEN AS GV1


--Q81
SELECT GV.MAGV, GV.HOTEN, GV.LUONG, (CASE
									WHEN GV.MAGV = BM.TRUONGBM AND GV.MAGV != K.TRUONGKHOA THEN 300
									WHEN GV.MAGV = K.TRUONGKHOA THEN 600
									END) AS 'PHUCAP'
FROM GIAOVIEN AS GV LEFT JOIN BOMON AS BM ON BM.MABM = GV.MABM 
LEFT JOIN KHOA AS K ON K.MAKHOA = BM.MAKHOA

--Q82
SELECT (CASE GV.PHAI
		WHEN N'Nam' THEN YEAR(NGSINH) + 60 
		WHEN N'Nữ' THEN YEAR(NGSINH) + 55
		END) AS 'NAMDUKIENNGHIHUU'
FROM GIAOVIEN AS GV 